apiVersion: v1
kind: Pod
metadata:
  name: podselector-label-require-1
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v7
    imagePullPolicy: IfNotPresent
---
# pod对象将被调度到持有app=myapp的pod对象所在节点
apiVersion: v1
kind: Pod
metadata:
  name: podselector-label-require-2
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh","-c","sleep 3600"]
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels: {app: myapp}
        topologyKey: kubernetes.io/hostname
